# Generated by Django 4.2.4 on 2023-08-24 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('serial_number', models.CharField(max_length=255)),
                ('condition', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.company')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('departments', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=2555)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.company')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_quantity', models.SmallIntegerField(default=1)),
                ('chekout_note', models.TextField(max_length=1000, null=True)),
                ('checkout_condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('broken', 'Broken')], default='good', max_length=10)),
                ('return_quantity', models.SmallIntegerField(default=0)),
                ('returned_note', models.TextField(max_length=1000, null=True)),
                ('returned_condition', models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('broken', 'Broken')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuing_time', models.DateTimeField(auto_now_add=True)),
                ('checkout_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_checked_out', to='Tracking.staff')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.employee')),
                ('returned_by_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_returned', to='Tracking.staff')),
            ],
        ),
    ]
