# Generated by Django 4.2.4 on 2023-08-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0002_alter_device_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicelog',
            old_name='checkin_time',
            new_name='return_time',
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='checkout_time',
            field=models.DateTimeField(),
        ),
    ]
