# Generated by Django 4.2.4 on 2023-08-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0003_rename_checkin_time_devicelog_return_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='checkout_time',
            field=models.DateField(),
        ),
    ]
